{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hibernate.reactive",
    "module": "hibernate-reactive-core",
    "version": "2.0.2.unity-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.6.Final"
          }
        },
        {
          "group": "io.smallrye.reactive",
          "module": "mutiny",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "hibernate-reactive-core-2.0.2.unity-SNAPSHOT.jar",
          "url": "hibernate-reactive-core-2.0.2.unity-SNAPSHOT.jar",
          "size": 1212275,
          "sha512": "633c44fb324214ece9c93a393a077f2c5b6f407a185e6fb2d5bd76cc949909035e3e82a79a911678a343c1b04425d4e38a421eec489ab59177bbcdb08eb18fff",
          "sha256": "8047b5a3eda13363dee94ef51755a3a01f1163afb263c1ce037888fe6bfa462b",
          "sha1": "7e0451599c0efa472170ec006ee6eca31d7c4c54",
          "md5": "d433fd7c9da56c30ef3aae18989a4f50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jboss.logging",
          "module": "jboss-logging",
          "version": {
            "requires": "3.5.0.Final"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-sql-client",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.6.Final"
          }
        },
        {
          "group": "io.smallrye.reactive",
          "module": "mutiny",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "hibernate-reactive-core-2.0.2.unity-SNAPSHOT.jar",
          "url": "hibernate-reactive-core-2.0.2.unity-SNAPSHOT.jar",
          "size": 1212275,
          "sha512": "633c44fb324214ece9c93a393a077f2c5b6f407a185e6fb2d5bd76cc949909035e3e82a79a911678a343c1b04425d4e38a421eec489ab59177bbcdb08eb18fff",
          "sha256": "8047b5a3eda13363dee94ef51755a3a01f1163afb263c1ce037888fe6bfa462b",
          "sha1": "7e0451599c0efa472170ec006ee6eca31d7c4c54",
          "md5": "d433fd7c9da56c30ef3aae18989a4f50"
        }
      ]
    }
  ]
}
